ARG  NODE_VERSION
FROM node:${NODE_VERSION:-20.13.1-alpine3.19}

WORKDIR /app
RUN corepack enable

COPY package.json yarn.lock /app/
RUN yarn install

ARG API
ARG NUXT_PUBLIC_SENTRY_DSN
ARG NUXT_PUBLIC_SENTRY_ENVIRONMENT
ENV API=${API}
ENV NUXT_PUBLIC_SENTRY_DSN=${NUXT_PUBLIC_SENTRY_DSN}
ENV NUXT_PUBLIC_SENTRY_ENVIRONMENT=${NUXT_PUBLIC_SENTRY_ENVIRONMENT}

COPY . .
RUN yarn install
RUN yarn build

EXPOSE 3000
CMD [ "node", ".output/server/index.mjs" ]
